Solve issue with .encode('ascii') in python 3.5, replaced by to_text  method
Don't use --no-color option because replaced by --no-ansi to ensure compatibility

The full traceback is:
Traceback (most recent call last):
  File "/tmp/ansible_y084ix0x/ansible_module_docker_service.py", line 1068, in <module>
    main()
  File "/tmp/ansible_y084ix0x/ansible_module_docker_service.py", line 1063, in main
    result = ContainerManager(client).exec_module()
  File "/tmp/ansible_y084ix0x/ansible_module_docker_service.py", line 657, in exec_module
    result = self.cmd_up()
  File "/tmp/ansible_y084ix0x/ansible_module_docker_service.py", line 753, in cmd_up
    cleanup_redirection_tempfiles(out_redir_name, err_redir_name)
  File "/tmp/ansible_y084ix0x/ansible_module_docker_service.py", line 515, in cleanup_redirection_tempfiles
    get_redirected_output(err_name)
  File "/tmp/ansible_y084ix0x/ansible_module_docker_service.py", line 524, in get_redirected_output
    new_line = re.sub(r'\x1b\[.+m', '', line.encode('ascii'))
  File "/usr/lib/python3.5/re.py", line 182, in sub
    return _compile(pattern, flags).sub(repl, string, count)
TypeError: cannot use a string pattern on a bytes-like object