Bump minimum openstacksdk version for openstack modules
With the addition of [a], the minimum openstacksdk version needs to
be bumped to include [b], or the os_network module will return the
error:

TypeError: create_network() got an unexpected keyword argument 'dns_domain'

[a] https://github.com/ansible/ansible/commit/6c74e29618a6872bc0da66e4992cfcd9cebf6acc
[b] https://github.com/openstack/openstacksdk/commit/a3e846e2b9301f4ae725e97b21b4313bfcc81d10
Fixes: #64495
Fixes: #64841