Update intro_installation.rst
To fix following issue while installing ansible on centos:
No package ansible available.
Error: Nothing to do

we need to install epel-release.Added this missing step