vmware_host_config_manager: avoid failure if no change
If nothing was changed, the module was raising the following error
because the `message` variable was not defined:

```
line 192, in set_host_configuration_facts
UnboundLocalError: local variable 'message' referenced before assignment
```