Chdir() back to where we were invoked from
Since we need to chdir() to ANSIBLE_HOME, we need to restore that after
env-setup, else e.g. ansible-playbook can't find any files referenced
relatively, e.g.

% ansible-playbook motd.yml --list-hosts
ERROR: the playbook: motd.yml could not be found

Signed-off-by: martin f. krafft <madduck@madduck.net>