commit 290ecfcdc2fa6dcbee8328130c85916fdebd5152 Author: Ton Kersten <github@tonkersten.com> Date:   Mon Apr 29 10:44:30 2013 +0200
    Fixed the installation of library directories

    When running install the `setup.py` give error

    changing mode of /usr/bin/ansible-doc to 755
    running install_data
    error: can't copy './library/utilities': doesn't exist or not a regular file
    make: *** [install] Error 1

    Debugging 'benno' came up with this patch, which works on CentOS 6.4 and
    on Ubuntu.