RHSM: use 'remove' instead of deprecated 'unregister'
The new command to unregister is 'remove':

$ subscription-manager -h
remove         Remove all or specific subscriptions from this system
unsubscribe    Deprecated, see remove

And also requires one of --serial, --pool or --all.

$ subscription-manager remove
Error: This command requires that you specify one of --serial, --pool or --all.

This patch:
* switch unregister to remove.
* adds --all by default to remove any subscription on the host.