Improve error reporting when parsing an ini file.
If an executable bit is removed from a hosts file that is a python script
the inventory will be parsed as ini and the output isn't very helpful
in debugging why this would be the case.

This changes the error:

errror: ansible.errors.AnsibleError: Invalid ini entry: sys - need more than 1 value to unpack

to this:

ansible.errors.AnsibleError: Invalid ini entry in /path/to/scripts/hosts/nova.py:20. Line was: 'import sys'. Expected format is 'variable=value'