cloud: ovirt: Add TypeError to except when calling getEntity.
When trying to add a storage domain to a Data Center using the
following:
    - ovirt_storage_domains:
           name: "initial_NFS"
           host: host_name
           data_center: "Default"
           auth:
                    username: "{{ username }}"
                    password: "{{ password }}"
                    url: "{{ url }}"
           nfs:
                    address: "{{ item.address }}"
                    path: "{{ item.path }}"
           with_items:
                    - "{{ initial_NFS }}"

The storage domain is added but could not be attached since a
TypeError exception is being thrown.

As part of adding new storage domain procedure the post_create_check validates
whether the storage domain exists or not, using the following API:
  /datacenters/111/storagedomains/111

If the storage domain is not attached the response header (see *)
does not contains any content type which leads to the following
exception once expected_re.match(actual) is being executed:
 TypeError: expected string or buffer

(*)
 [u'HTTP/1.1 404 Not Found\r',
  u'Connection: keep-alive\r',
  u'Content-Length: 0\r',
  u'Correlation-Id: 6e4fedec-4923-4225-9b86-ad6feba60e77\r',
  u'Date: Sun, 23 Apr 2017 16:40:46 GMT\r', u'\r', u'']

WIP: Perhaps a proper fix might be used by avoiding to call match
if the response code 404 (Not found)