[packaging/rpm] %{python_sitelib} breaks RHEL8
Change:
Modern RHEL8 dislikes unversioned python macros, and will error on them:

Start: rpmbuild -bs
error: attempt to use unversioned python, define %__python to /usr/bin/python2 or /usr/bin/python3 explicitly
error: line 222: if expr x'%{python_sitelib}' : 'x.*dist-packages/\?' ; then

We actually work around this earlier in the spec file, but the static
analysis that rpmbuild does is not smart enough to realize that we're
using our custom %{python_sitelib} global here.

So this PR just renames it to %{_python_sitelib} instead to sate
rpmbuild and get the spec file working on el8.

Test Plan:
Built on RHEL8 VM successfully.

Signed-off-by: Rick Elrod <rick@elrod.me>