Fixes this issue with the ec2 module:
    module.exit_json(changed=changed, instance_ids=new_instance_ids, instances=instance_dict_array, tagged_instances=tagged_instances\
)
UnboundLocalError: local variable 'tagged_instances' referenced before assignment

Which was introduced with this commit: https://github.com/ansible/ansible/commit/70ebb051907e1716c8ea62f4dacdea39a6071e55