Pip module: fixing issue with python 2.4 support
Python 2.4.3 returns:
TypeError: expected character buffer object

startswith is expecting only a string instead of a tuple like newer versions allow.