fix vmware_guest adding cdrom to existing ide controller
`create_ide_controller()` returns a `vim.vm.device.VirtualDeviceSpec`
`get_vm_ide_device()` returns a `vim.vm.device.VirtualIDEController`
Both were getting assigned to the `ide_device` variable, which got passed to `create_cdrom()`, which assumed the value was a `VirtualDeviceSpec`, and so would fail with `AttributeError: 'int[]' object has no attribute 'key'` when trying to access `ide_ctl.device.key`.

This fixes the issue by ensuring that the variable is always a `vim.vm.device.VirtualIDEController`. This commit also changes variable and function naming around this area to clear up the confusion.