Fixed ansible 2 python API example [ci skip]
The example crashes without the default options: AttributeError:
'Options' object has no attribute 'remote_user'

Turns out there are a lot of default options we need and that's the
shortest way to get them.