Update secrets.py example to include 'datacenter'
When relying on secrets.py omitting the 'datacenter' field from GCE_KEYWORK_PARAMS results in the below exception being thrown:
```
$ ./gce.py 
Traceback (most recent call last):
  File "./gce.py", line 508, in <module>
    GceInventory()
  File "./gce.py", line 170, in __init__
    self.driver = self.get_gce_driver()
  File "./gce.py", line 315, in get_gce_driver
    kwargs['datacenter'] = os.environ.get('GCE_ZONE', kwargs['datacenter'])
KeyError: 'datacenter'
```
As this can be easily avoided by supplying an empty argument I would like to propose the document is updated to avoid confusion for new users.  I will also make a change request for gce.py to make it more gracefully handle the datacenter parameter being omitted.