Fix dictionary access in os_floating_ip module
When using `nat_destination` parameter of `os_floating_ip` module, dot
syntax (`addr.addr`) is used to access a value in a dictionary,
resulting in the module crashing with this error:

AttributeError: 'dict' object has no attribute 'addr'

This is now fixed, when using correct syntax (`addr['addr']`), the
module seems to work fine.

Fixes #51443