[backport 2.8] Bump min openstacksdk version for os_network/port_security_enabled
To make use of the port_security_enabled [a] parameter, [b] needs
to be present in the openstacksdk or the os_network module will
return an error like:

TypeError: create_network() got an unexpected keyword argument 'port_security_enabled'

To handle this, we fail the module if one of the arguments are used
and the minimum openstacksdk version for that argument is not met.

[a] https://github.com/ansible/ansible/commit/eaf238b033a0504c48440cf85982a2b89851059d
[b] https://github.com/openstack/openstacksdk/commit/8eb788af07ed88166db7b8a58ce1fecacd7a29b1

Backport-of: https://review.opendev.org/708119
Fixes: #62062