vmware_rest_client: pass object to get_tags_for_dynamic_obj
This patch fix the `vmware_cluster_info` functional-tests.
`get_tags_for_dynamic_obj()` expects an object, not the object ID in a
string.

Without this patch, the `vmware_cluster_info` module fails.
`get_tags_for_object()` raises the following exception:

```
vmware.vapi.exception.CoreException: Expected VapiStruct instance or python dictionary, but received str
```

The patch partially reverts changes introduce in:
https://github.com/ansible/ansible/commit/35cc26f8c0447ab1ad4427eafcc7283c4356370d

See: http://vmware.github.io/vsphere-automation-sdk-rest/6.5/operations/com/vmware/cis/tagging/tag_association.list_attached_tags-operation.html