Update nxos_vlan.py
I was getting playbook failures of this form:
for i in interfaces.split(','):\nAttributeError: 'list' object has no attribute 'split'\n"
after upgrading 2.4-->2.5 
Removing the .split() function causes my playbook to work successfully.