[stable-2.5] HashiVault: fix AttributeError when auth_method != 'token' (#36513) (#45243)
* Fixed `'HashiVault' object has no attribute 'verify'"}` (#36513)


(cherry picked from commit 0ceb717cae8da219016b6afd1c25382d4fb538fc)

* Add changelog entry

* Update hashi_vault_fix_object_has_no_attribute_verify