Make _to_filesystem_str return a string on py3
On python 3, this return a bytes object, so this fail
with the following traceback:

    Traceback (most recent call last):
      File \"/tmp/ansible_rs2o3x04/ansible_module_authorized_key.py\", line 499, in <module>
        main()
      File \"/tmp/ansible_rs2o3x04/ansible_module_authorized_key.py\", line 493, in main
        results = enforce_state(module, module.params)
      File \"/tmp/ansible_rs2o3x04/ansible_module_authorized_key.py\", line 468, in enforce_state
        writekeys(module, keyfile(module, user, do_write, path, manage_dir), existing_keys)
      File \"/tmp/ansible_rs2o3x04/ansible_module_authorized_key.py\", line 371, in writekeys
        module.atomic_move(tmp_path, filename)
      File \"/tmp/ansible_rs2o3x04/ansible_modlib.zip/ansible/module_utils/basic.py\", line 1905, in atomic_move
      File \"/tmp/ansible_rs2o3x04/ansible_modlib.zip/ansible/module_utils/basic.py\", line 816, in selinux_context
    TypeError: in method 'lgetfilecon_raw', argument 1 of type 'char const *'