gather_subset is a list of strings
When gather_subset is an integer, a message pointing out the problem
will be displayed.

The current error:

    The full traceback is:
    Traceback (most recent call last):
      File "tmp/ansible-tmp-1534089772.5756419-196565636905886/AnsiballZ_setup.py", line 113, in <module>
        _ansiballz_main()
      File "ansible-tmp-1534089772.5756419-196565636905886/AnsiballZ_setup.py", line 105, in _ansiballz_main
        invoke_module(zipped_mod, temp_path, ANSIBALLZ_PARAMS)
      File "ansible-tmp-1534089772.5756419-196565636905886/AnsiballZ_setup.py", line 48, in invoke_module
        imp.load_module('__main__', mod, module, MOD_DESC)
      File "__main__.py", line 184, in <module>
      File "__main__.py", line 176, in main
      File "ansible_setup_payload.zip/ansible/module_utils/facts/ansible_collector.py", line 124, in get_ansible_collector
      File "ansible_setup_payload.zip/ansible/module_utils/facts/collector.py", line 388, in collector_classes_from_gather_subset
      File "ansible_setup_payload.zip/ansible/module_utils/facts/collector.py", line 165, in get_collector_names
    AttributeError: 'int' object has no attribute 'startswith'

is replaced by this one:

    ERROR! the field 'gather_subset' should be a list of (<class 'str'>,), but the item '42' is a <class 'int'>

    The error appears to have been in 'play.yml': line 1, column 3, but may
    be elsewhere in the file depending on the exact syntax problem.

    The offending line appears to be:

    - hosts: all
      ^ here