Update macOS installation instructions
##### SUMMARY
<!--- Your description here -->

On macOS Catalina ``pip install --user ansible`` results in warnings and errors. There are quite a [few bad or very unsafe answers]( https://stackoverflow.com/questions/45954528/pip-is-configured-with-locations-that-require-tls-ssl-however-the-ssl-module-in/59280089#59280089) out there, and this updates the reference documents to reflect changes Catalina+ with a safe, easy install for Ansible.

    WARNING: pip is being invoked by an old script wrapper. This will fail in a future version of pip.
    WARNING: pip is configured with locations that require TLS/SSL, however the ssl module in Python is not available.
    WARNING: Retrying (Retry(total=4, connect=None, read=None, redirect=None, status=None)) after connection broken by 'SSLError("Can't connect to HTTPS URL because the SSL module is not available.")': /simple/ansible/
    .... (previous warning repeated)
    ERROR: Could not find a version that satisfies the requirement ansible (from versions: none)
    ERROR: No matching distribution found for ansible
    WARNING: pip is configured with locations that require TLS/SSL, however the ssl module in Python is not available.

Therefore, it's bests to access pip as a module and run: 

    python -m pip install --user ansible

And so forth.

##### ISSUE TYPE
- Docs Pull Request

+label: docsite_pr