Fix unset ansible_virtualization_role (#39514) (#39885)
Error was:
AttributeError("'str' object has no attribute 'startwith'",)

Closes #39138

(cherry picked from commit 2397ca1a7e15a1a6941b07a5a1e3a52837ee9d7c)