Lock azure-mgmt-containerservice to 1.0.0.
Attempting to create an Azure Container Service cluster results in an exception, apparently because the API of `azure.mgmt.containerservice.models.ContainerServiceMasterProfile` changed in 2.0.0:

```
Traceback (most recent call last):
  File "/var/folders/80/3373r54x51x__g9svfyxbr1c0000gn/T/ansible_rqtXta/ansible_module_azure_rm_acs.py", line 719, in <module>
    main()
  File "/var/folders/80/3373r54x51x__g9svfyxbr1c0000gn/T/ansible_rqtXta/ansible_module_azure_rm_acs.py", line 716, in main
    AzureRMContainerService()
  File "/var/folders/80/3373r54x51x__g9svfyxbr1c0000gn/T/ansible_rqtXta/ansible_module_azure_rm_acs.py", line 513, in __init__
    supports_tags=True)
  File "/var/folders/80/3373r54x51x__g9svfyxbr1c0000gn/T/ansible_rqtXta/ansible_modlib.zip/ansible/module_utils/azure_rm_common.py", line 256, in __init__
  File "/var/folders/80/3373r54x51x__g9svfyxbr1c0000gn/T/ansible_rqtXta/ansible_module_azure_rm_acs.py", line 617, in exec_module
    self.results['state'] = self.create_update_acs()
  File "/var/folders/80/3373r54x51x__g9svfyxbr1c0000gn/T/ansible_rqtXta/ansible_module_azure_rm_acs.py", line 652, in create_update_acs
    master_profile=create_master_profile_instance(self.master_profile),
  File "/var/folders/80/3373r54x51x__g9svfyxbr1c0000gn/T/ansible_rqtXta/ansible_module_azure_rm_acs.py", line 328, in create_master_profile_instance
    dns_prefix=masterprofile[0]['dns_prefix']
TypeError: __init__() takes at least 3 arguments (3 given)
```

Locking the dependency to 1.0.0 solves the error until the module can be updated to the new API.