Fix mkstemp() usage in jenkins_plugin.py
Commit ac0e6d2c tried to make the creation of temporary file more
secure. However, the return values of mkstemp() were not handled
correctly, which resulted in the following error:

Traceback (most recent call last):
  File "/tmp/ansible_2VBlrF/ansible_module_jenkins_plugin.py", line 829, in <module>
    main()
  File "/tmp/ansible_2VBlrF/ansible_module_jenkins_plugin.py", line 812, in main
    changed = jp.install()
File "/tmp/ansible_2VBlrF/ansible_module_jenkins_plugin.py", line 495, in install
    self._write_file(plugin_file, data)
  File "/tmp/ansible_2VBlrF/ansible_module_jenkins_plugin.py", line 646, in _write_file
    fd = open(tmp_f, 'wb')
TypeError: coercing to Unicode: need string or buffer, tuple found

This patch attempts to fix this bug by properly consuming the
return values for mkstemp() and and taking care of open FDs.