Tests were failing with this error message, introduced by 9ea54fcaaf
ERROR: test_check_conditional_jinja2_variable_literals (TestUtils.TestUtils)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/misc/checkout/git/ansible/test/TestUtils.py", line 151, in test_check_conditional_jinja2_variable_literals
    'jinja2_compare var', '/', {'var': 1}) == True)
  File "/home/misc/checkout/git/ansible/lib/ansible/utils/__init__.py", line 178, in check_conditional
    original = conditional.replace("jinja2_compare ","")
AttributeError: 'int' object has no attribute 'replace'