Fix self.groups in inventory when override_hosts is set
This sets self.groups to the values returned from
_groups_from_override_hosts() so that it is a list.  Otherwise, this
fails with:
    AttributeError: 'str' object has no attribute 'get_hosts'
The str object is the string 'all', the key in the dict returned by the
method in question.