Support inventory scripts that are not in PATH.
Without this change, the following fails, assuming that . is not in
PATH:

$ cd /tmp
$ cp .../plugins/inventory/ec2.* .
$ ansible -i ec2.py all -m ping
ERROR: problem running ec2.py --list ([Errno 2] No such file or directory)