VMware: fix hw_guest_ha_state fact
vm.summary.runtime.dasVmProtection isn't printable/json-able.

If we try to pass it to exit_json, it raise an exception:
```
TypeError: Value of unknown type: <class 'pyVmomi.VmomiSupport.vim.vm.RuntimeInfo.DasProtectionState'>, (vim.vm.RuntimeInfo.DasProtectionState) ...
```

https://www.vmware.com/support/developer/converter-sdk/conv60_apireference/vim.vm.RuntimeInfo.html

vm.summary.runtime.dasVmProtection is of type
VirtualMachineRuntimeInfoDasProtectionState

https://www.vmware.com/support/developer/converter-sdk/conv60_apireference/vim.vm.RuntimeInfo.DasProtectionState.html

which contain a dasProtected properties, which is a boolean.

So if vm.summary.runtime.dasVmProtection is defined, we want to return
vm.summary.runtime.dasVmProtection.dasProtected (not the whole object).