Fix ssh_config.py bug with IdentityFile
When IdentityFile is specified in an ssh config file, using the ssh_config.py
inventory plugin would yield the error:

AttributeError: 'list' object has no attribute 'startswith'

This is because Paramiko returns a list of private key paths when parsing the
ssh config, and Ansible expects a string.

This commit fixes the issue by taking the first element in the list returned by
Paramiko.