Updated nmcli.py for several versions
Errors found/fixed and now working on all tested Red Hat versions:

- 7.0: nmcli too version 0.9.9.1-13.git20140326.4dba720.el7
- 7.6: nmcli tool, version 1.12.0-10.el7_6
- 7.7: nmcli tool, version 1.18.0-5.el7



1. Conversion

__Error__
```
TypeError: argument of type 'int' is not iterable
```

__Fix__

Added line 587
```
from ansible.module_utils._text import to_text
```

Replaced several lines:
```
sed -i 's/cmd.extend(\[key, value\])/cmd.extend(\[key, to_text(value)\])/g' /usr/lib/python2.7/site-packages/ansible/modules/net_tools/nmcli.py
```


2. NMCLI syntax

__Error__
```
Error: invalid <setting>.<property> 'autoconnect'.
```

__Reproduce__

Working/Not Working
```
[root@localhost ~]# nmcli con mod enp0s3 connection.autoconnect yes
[root@localhost ~]# nmcli con mod enp0s3 autoconnect yes
Error: invalid <setting>.<property> 'autoconnect'.
[root@localhost ~]# 
```

__Fix__
```
Added 'connection.autoconnect' to the nmcli.py rather than 'autoconnect'
```


3. NMCLI version and NM-glib package dependency

__Error__
```
The error was: ValueError: Namespace NMClient not available
"msg": "Failed to import the required Python library (NetworkManager glib API)"
```

__Fix__
```
try/except block code lines 566 to 582
```